function indent(text, level = 1) {
  const padding = '  '.repeat(level)
  return text
    .split('\n')
    .map(line => (line ? `${padding}${line}` : line))
    .join('\n')
}

function schemaRefToType(ref) {
  return ref.split('/').at(-1)
}

function union(items) {
  return [...new Set(items)].join(' | ') || 'never'
}

export function schemaToTs(schema, fallback = 'unknown') {
  if (!schema) {
    return fallback
  }

  if (schema.$ref) {
    return schemaRefToType(schema.$ref)
  }

  if (schema.oneOf) {
    return union(schema.oneOf.map(item => schemaToTs(item)))
  }

  if (schema.allOf) {
    return union(schema.allOf.map(item => schemaToTs(item))).replace(/\s\|\s/g, ' & ')
  }

  if (schema.enum) {
    return union(schema.enum.map(value => JSON.stringify(value)))
  }

  if (schema.const !== undefined) {
    return JSON.stringify(schema.const)
  }

  if (schema.type === 'array') {
    return `(${schemaToTs(schema.items)})[]`
  }

  if (schema.type === 'object' || schema.properties) {
    const properties = schema.properties || {}
    const required = new Set(schema.required || [])
    const lines = Object.entries(properties).map(([key, value]) => {
      const optional = required.has(key) ? '' : '?'
      return `${key}${optional}: ${schemaToTs(value)}`
    })

    if (schema.additionalProperties === true) {
      lines.push('[key: string]: unknown')
    } else if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
      lines.push(`[key: string]: ${schemaToTs(schema.additionalProperties)}`)
    }

    if (lines.length === 0) {
      return 'Record<string, unknown>'
    }

    return `{\n${indent(lines.join('\n'))}\n}`
  }

  switch (schema.type) {
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'string':
      return 'string'
    default:
      return fallback
  }
}

function renderSchemas(spec) {
  const schemas = spec.components?.schemas || {}
  const blocks = Object.entries(schemas).map(([name, schema]) => `export type ${name} = ${schemaToTs(schema)}\n`)
  return blocks.join('\n')
}

function extractRequestType(operation) {
  const schema =
    operation.requestBody?.content?.['application/json']?.schema ||
    operation.requestBody?.content?.['multipart/form-data']?.schema
  return schema ? schemaToTs(schema) : 'undefined'
}

function extractResponsesType(operation) {
  const responses = operation.responses || {}
  const entries = Object.entries(responses).map(([status, response]) => {
    const schema = response.content?.['application/json']?.schema
    return `${JSON.stringify(status)}: ${schema ? schemaToTs(schema) : 'undefined'}`
  })
  return `{\n${indent(entries.join('\n'))}\n}`
}

function renderOperations(spec) {
  const blocks = []

  for (const [path, methods] of Object.entries(spec.paths || {})) {
    for (const [method, operation] of Object.entries(methods)) {
      blocks.push(
        `${JSON.stringify(operation.operationId)}: {\n` +
          indent(`method: ${JSON.stringify(method.toUpperCase())}\npath: ${JSON.stringify(path)}\nrequestBody: ${extractRequestType(operation)}\nresponses: ${extractResponsesType(operation)}`) +
          `\n}`,
      )
    }
  }

  return `export interface Operations {\n${indent(blocks.join('\n'))}\n}\n`
}

export function generateTypeDeclarations(spec) {
  return `/* eslint-disable */\n/* auto-generated by spec/documentacion/scripts/generate-types.mjs */\n\n${renderSchemas(spec)}\n${renderOperations(spec)}`
}
